# Generated by Django 6.0.3 on 2026-04-15 05:40

from django.db import migrations

CATEGORIES = [
    ('Electronics', 'Phones, laptops, chargers, headphones, and other electronic devices'),
    ('Documents', 'IDs, passports, student cards, certificates, and other documents'),
    ('Clothing', 'Jackets, hats, scarves, gloves, and other clothing items'),
    ('Accessories', 'Watches, jewelry, glasses, keys, and other accessories'),
    ('Bags', 'Backpacks, handbags, wallets, purses, and other bags'),
]


def seed_categories(apps, schema_editor):
    Category = apps.get_model('api', 'Category')
    for name, description in CATEGORIES:
        Category.objects.get_or_create(name=name, defaults={'description': description})


def remove_categories(apps, schema_editor):
    Category = apps.get_model('api', 'Category')
    Category.objects.filter(name__in=[name for name, _ in CATEGORIES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_categories, remove_categories),
    ]
